### ISSUE TITLE
PyG Temporal Citation

### ISSUE THREAD

**Issue by benedekrozemberczki** [fterroso/tourist_mob#1]
Dear @fterroso,

I have seen that you have used PyG temporal on the project. Can you cite it in the final manuscript?

Bests,

Benedek

**Comment by fterroso** [comment]
Hi Benedek,
yes, we actually cite your work in the final version of the manuscript. See reference [41] in the open access version: https://www.sciencedirect.com/science/article/pii/S1566253522002159#b41
Thank you,
Fernando.
